Prefix: "&b&lNASGAR >> &7"
Interval: 3600 # EN SEGUNGOS (3600 SEGUNDOS = 1 HORA)
# Este formato es si desea anunciar manualmente con /announce <message>
# Si esto está deshabilitado, el comando tendrá el prefijo en su lugar
# Permiso para usar este comando es - nasgarannounce.use
Formato:
  ACTIVADO: true
  LINEAS:
    - "&8&m-------------------------------------------------"
    - "&8{arrow} &b&lNasgar"
    - ""
    - "&8{arrow} &7{message}"
    - ""
    - "&8&m-------------------------------------------------"
Anuncios:
  EJEMPLO:
    LINEAS:
      - "&8&m-------------------------------------------------"
      - "&8{arrow} &b&lNASGAR &8| &f&lEJEMPLO!"
      - ""
      - "&8{arrow} &7Este es un ejemplo de anuncio!"
      - "&8{arrow} &7edita muchos anuncios en mi configuracion!"
      - ""
      - "&8{arrow} &7Plugin desarrolado por AYisGOD"
      - "&8&m-------------------------------------------------"